on: [push, pull_request]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [stable, oldstable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test ./...
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret
      - uses: actions/setup-go@v3
        with:
          go-version: stable
      - uses: actions/checkout@v3
      - run: |
          export VERTEX_API_KEY=$(gcloud auth $VERTEX_PROJECT print-access-token)
          go test -tags=integration ./...
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
  gocritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - run: |
          go install github.com/go-critic/go-critic/cmd/gocritic@latest
          gocritic check .
        
