on: [push, pull_request]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [stable, oldstable]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test ./...
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: stable
      - uses: actions/checkout@v3
      - id:   'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDS }}'
      - name: Set up GCloud CLI
        uses: 'google-github-actions/setup-gcloud@v1'
      - run: |
          export VERTEX_API_KEY=$(gcloud auth print-access-token) && \
          export VERTEX_PROJECT=${{ secrets.VERTEX_PROJECT }} && \
          export && \
          go test -tags=integration ./...
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
  gocritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      - run: |
          go install github.com/go-critic/go-critic/cmd/gocritic@latest
          gocritic check .
        
